### ISSUE TITLE
SQLSTATE[22007]:

### ISSUE THREAD

**Issue by room3622** [kolodny/Db.class.php#1]
$user = new Character();
$user->name = "teste";
$user->create();

 public function create() {
        global $database;
        $attributes = $this->sanitized_attributes();
        $sql = "INSERT INTO ".self::$table_name." (";
        $sql .= join(", ", array_keys($attributes));
        $sql .= ") VALUES ('";
        $sql .= join("', '", array_values($attributes));
        $sql .= "')";

        $database->query($sql);

    }

sql created ==== INSERT INTO character (id, name) VALUES ('', 'teste')

and i get this error 
SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column 'id' at row 1

**Comment by kolodny** [comment]
This issue isn't even using this library. Is there something in this repo that isn't working? Feel free to reopen if I'm missing something
